services:
  starter-monorepo-database:
    platform: linux/amd64
    image: mysql
    container_name: starter-monorepo-database
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=contact-apps
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    networks:
      - starter-monorepo-networks
    volumes:
      - starter-monorepo-volumes:/var/lib/mysql
      - ./contact_app_contacts.sql:/docker-entrypoint-initdb.d/contact-apps.sql
  starter-monorepo-server:
    platform: linux/amd64
    image: gatherloop/starter-monorepo-server
    container_name: starter-monorepo-server
    environment:
      - HOST=starter-monorepo-database
      - PORT=3306
      - USERNAME=root
      - PASSWORD=root
      - DATABASE_NAME=contact-apps
      - SERVER_PORT=3000
    ports:
      - 5101:3000
    depends_on:
      starter-monorepo-database:
        condition: service_healthy
    networks:
      - starter-monorepo-networks
  starter-monorepo-user-facing:
    platform: linux/amd64
    image: gatherloop/starter-monorepo-user-facing
    container_name: starter-monorepo-user-facing
    environment:
      - API_URL=https://gw-starter.gatherloop.co
    ports:
      - 5100:3000
    networks:
      - starter-monorepo-networks

networks:
  starter-monorepo-networks:
    name: starter-monorepo-networks
volumes:
  starter-monorepo-volumes:
    name: starter-monorepo-volumes
